version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\wellington\go-libsass

environment:
  GOPATH: c:\gopath
  CGO_ENABLED: 1
  GOROOT_BOOTSTRAP: C:\go
  GOROOT: C:\go15\go
  GO15VENDOREXPERIMENT: 1

cache:
  - C:\mingw64 -> appveyor.yml
  - C:\go15 -> appveyor.yml

install:
  # install nodejs and npm
  # - ps: Install-Product node $env:nodejs_version
  # install gcc (needed for sqlite3)
  #- choco install -y mingw
  - set PATH=C:\mingw64\bin;C:\go15\go\bin;C:\gopath\bin;%PATH%
  #retrieve go 1.5
  - ps: |
      # $file = "go1.5.1.windows-amd64.zip"
      # $url  = "https://bintray.com/artifact/download/drewwells/generic/"
      $file = "go1.6beta1.windows-amd64.zip"
      $url = "https://storage.googleapis.com/golang/"
      $url += $file
      $goAUTHOR="C:\go15\go\AUTHORS"
      If (Test-Path $goAUTHOR){
        Write-Host "Using cached Go"
      }Else{
        Write-Host "Fetching Go"
        Invoke-WebRequest -UserAgent wget -Uri $url -OutFile $file
        &7z x -oC:\go15 $file > $null
      }
  - dir C:\go15
  - go version
  - ps: |
      # Install MinGW.
      $url = "https://bintray.com/artifact/download/drewwells/generic/x86_64-5.1.0-release-win32-seh-rt_v4-rev0.7z"
      $strFileName="C:\mingw64\bin\mingw32-make.exe"
      If (Test-Path $strFileName){
        Write-Host "Using cached mingw64"
      }Else{
        Write-Host "Fetching mingw64"
        Invoke-WebRequest -UserAgent wget -Uri $url -OutFile ming32-64.7z
        &7z x -oC:\ ming32-64.7z > $null
      }
  - set CC=gcc
  - set CXX=g++
  - echo %PATH%
  - echo %GOPATH%
  - dir C:\mingw64\bin
  - go get golang.org/x/net/context
  - go test

build_script:
  - go build -x -ldflags "-extldflags '-static'"
