version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/go:1.15.3'
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD
        environment:
          CC: gcc
          CXX: g++
          GOPATH: /home/ubuntu/.go_workspace
          GOVER: 1.7.1
          GOTAR: /home/ubuntu/go${GOVER}.linux-amd64.tar.gz
    steps:
      - checkout
      - run:
          name: Unit tests
          command: |
            go version
            test -e ${GOTAR} || wget https://storage.googleapis.com/golang/go${GOVER}.linux-amd64.tar.gz -O ${GOTAR}
            go get golang.org/x/net/context
            go test -i -race $(go list -f '{{if len .TestGoFiles}}{{.ImportPath}}{{end}}' ./... | grep -v /vendor/)
